title: <p align="center"> Lekha Sharma </p>
logo: /assets/img/me1.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lekha-sharma1106">LinkedIn</a> |
  <a href="https://github.com/lekhasharma1106/">GitHub</a>
  <br>
  Result-oriented individual who is eager to leverage academic foundation and practical skills in data analysis tools 
  to contribute to cutting-edge projects, solve real-world problems
  <br></p>

theme: jekyll-theme-minimal
