title: <p align="center"> Lekha Sharma </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lekha-sharma1106">LinkedIn</a> |
  <a href="https://github.com/lekhasharma1106/">GitHub</a>
  
<br>   
Result-oriented individual successfully completed Executive Post Graduate Program in Data Science from IIIT-Banglore with specialization in Business Intelligance & Data Analytics.
Eager to leverage academic foundation and practical skills in data analytics, SQL and Power VI to contribute to cutting-edge projects, solve real-world problems.
Seeking an entry level opportunity as a Data Analyst/BI Analyst with an organization of repute.
<br>
</p>

theme: jekyll-theme-minimal
