title: <p align="center"> Lekha Sharma </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lekha-sharma1106">LinkedIn</a> |
  <a href="https://github.com/lekhasharma1106/">GitHub</a>
  <br>Result-oriented individual successfully completed Executive Post Graduate Program in Data Science from IIIT-Bangalore with specialization in Business Intelligence & Data Analytics.<br>
  eager to leverage academic foundation and practical skills in data analysis, SQL, and Power BI to contribute to cutting-edge projects, solve real-world problems<br>
  <br>
  </p>

theme: jekyll-theme-minimal
