title: <p align="center"> Lekha Sharma </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lekha-sharma1106">LinkedIn</a> |
  <a href="https://github.com/lekhasharma1106/">GitHub</a>
  <br>
  Result-oriented individual who is eager to leverage academic foundation and practical skills<br> in data analysis, SQL, and Power BI 
  to contribute to cutting-edge projects, solve real-world problems
  <br>
  </p>

theme: jekyll-theme-minimal
